ERROR: Expression::evaludate
initializer list class does not convert to NamedPoint class because there is a hidden std conversion through std::map

required: write Convert::initializerToMap<std::string, double>